### ISSUE TITLE
bin/sources.sh: no such file or directory

### ISSUE THREAD

**Issue by VPaulV** [Mazon/Jorgmundr#3]
Dear Mazon,

Looks like you didn't push all files to the master branch.

Removing intermediate container 8aff1ce0e52c
Step 3 : COPY bin/sources.sh /usr/local/bin/sources.sh
INFO[0292] bin/sources.sh: no such file or directory   

Best regards,

Paul

**Comment by Mazon** [comment]
Sorry, fixed. 
Im not 100% confident in the status of this image. Was a while since i hacked on it. If i remember correctly it does come up now. But i would like to move all the startups to supervisord in the future. Please let me know of any quirks and ill try fix it.
